// <auto-generated />
using Boolean;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Boolean.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240506201803_SpecialChannels")]
    partial class SpecialChannels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Boolean.Member", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<bool>("Administrator")
                        .HasColumnType("boolean")
                        .HasColumnName("administrator");

                    b.Property<decimal>("ServerSnowflake")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Snowflake")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("snowflake");

                    b.HasKey("Id");

                    b.HasIndex("ServerSnowflake");

                    b.ToTable("members");
                });

            modelBuilder.Entity("Boolean.Server", b =>
                {
                    b.Property<decimal>("Snowflake")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.HasKey("Snowflake");

                    b.ToTable("servers");
                });

            modelBuilder.Entity("Boolean.SpecialChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<decimal>("ServerSnowflake")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Snowflake")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("snowflake");

                    b.HasKey("Id");

                    b.HasIndex("ServerSnowflake");

                    b.ToTable("special_channels");
                });

            modelBuilder.Entity("Boolean.Member", b =>
                {
                    b.HasOne("Boolean.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerSnowflake")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Boolean.SpecialChannel", b =>
                {
                    b.HasOne("Boolean.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerSnowflake")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });
#pragma warning restore 612, 618
        }
    }
}
